apiVersion: v1
kind: Service
metadata:
  name: timeservice
  labels:
    app: time-service
spec:
  ports:
  - port: 9000
    name: http
  selector:
    app: time-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: time-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: time-service
        version: v1
    spec:
      containers:
      - name: time-service
        image: vkahawala/time-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
          - name: VERSION
            value: "1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: time-service-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: time-service
        version: v2
    spec:
      containers:
      - name: time-service
        image: vkahawala/time-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        env:
          - name: VERSION
            value: "2"